### ISSUE TITLE
investigate claim: ui is slow

### ISSUE THREAD

**Issue by nornagon** [nornagon/ur-a-dorf#17]
so says @sgentle

**Comment by nornagon** [comment]
hm, i measured and it's <5ms to render the whole UI on my machine. Closing this for now, @sgentle next time could you grab a perf trace if you encounter the issue again?

**Comment by sgentle** [comment]
Might just be slow on my phone, not sure...

Any chance you could put together some kind of backend mock that spits out random updates? Be happy to chase it down but I don't want to install dorf fortress because of the memetic hazard :D

**Comment by nornagon** [comment]
could do, probs easier to just come on the next time i stream. likely wednesday 6pmish PST again :)
